# Generated by Django 4.2.5 on 2023-09-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataupload',
            options={'verbose_name_plural': 'data_upload'},
        ),
    ]
