# Generated by Django 4.2.5 on 2023-09-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0002_alter_dataupload_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataupload',
            options={'verbose_name_plural': 'dataUpload'},
        ),
    ]
