# Generated by Django 4.2.5 on 2023-09-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0005_remove_dataupload_file_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('sources_of_water', models.BooleanField()),
                ('proximity_to_industries', models.CharField(max_length=255)),
                ('number_of_garages_in_area', models.IntegerField()),
                ('proximity_to_dumpsite', models.CharField(max_length=255)),
                ('presence_of_open_sewage', models.BooleanField()),
                ('past_cases_of_lead_poisoning', models.CharField(max_length=255)),
                ('women_and_children_population', models.IntegerField()),
            ],
        ),
    ]
