# Generated by Django 4.2.5 on 2023-09-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0006_extracteddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='sources_of_water',
            field=models.BooleanField(default=False),
        ),
    ]
