# Generated by Django 4.2.5 on 2023-09-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0007_alter_extracteddata_sources_of_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='presence_of_open_sewage',
            field=models.BooleanField(help_text='Check this box if there is an open sewage in your location'),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='sources_of_water',
            field=models.BooleanField(help_text='Check this box if your source of water is borehole'),
        ),
    ]
