# Generated by Django 4.2.5 on 2023-09-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0010_alter_dataupload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='file_upload_status',
            field=models.CharField(choices=[('Progress', 'progress'), ('uploaded', 'uploaded'), ('completed', 'comppleted')], max_length=16),
        ),
    ]
