# Generated by Django 4.2.5 on 2023-09-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0013_alter_dataupload_options_alter_extracteddata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='file_hash',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
