# Generated by Django 4.2.5 on 2023-09-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagetracking', '0002_alter_organizationstagetracking_stage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('Planning', 'Planning'), ('Testing', 'Testing'), ('Treating', 'Treating')], max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagetracking.organizationstagetracking')),
            ],
        ),
    ]
