# Generated by Django 4.2.5 on 2023-10-06 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('file_name', models.CharField(max_length=255)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'DataUpload',
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=159)),
                ('blood_lead_levels', models.CharField(default='', max_length=32)),
                ('file_hash', models.CharField(max_length=32)),
                ('file_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dataUpload.dataupload')),
            ],
            options={
                'verbose_name_plural': 'ExtractedData',
            },
        ),
    ]
