# Generated by Django 4.2.5 on 2023-10-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('file_name', models.CharField(max_length=255)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'DataUpload',
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=159)),
                ('sources_of_water', models.CharField(default='', max_length=32)),
                ('proximity_to_industries', models.CharField(default='', max_length=255)),
                ('number_of_garages_in_area', models.IntegerField(default=0)),
                ('proximity_to_dumpsite', models.CharField(default='', max_length=255)),
                ('presence_of_open_sewage', models.CharField(default='', max_length=32)),
                ('past_cases_of_lead_poisoning', models.IntegerField(default=0)),
                ('women_and_children_population', models.IntegerField(default=0)),
                ('file_hash', models.CharField(max_length=32)),
                ('lead_blood_levels', models.CharField(default='', max_length=32)),
                ('file_name', models.CharField(default='', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'ExtractedData',
            },
        ),
    ]
