# Generated by Django 4.2.5 on 2023-10-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracteddata',
            name='blood_lead_levels',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='lead_blood_levels',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='number_of_garages_in_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='past_cases_of_lead_poisoning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='presence_of_open_sewage',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='proximity_to_dumpsite',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='proximity_to_industries',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='sources_of_water',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='women_and_children_population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='file_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
