# Generated by Django 4.2.5 on 2023-09-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0004_dataupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataupload',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='file_upload_status',
            field=models.CharField(choices=[('pending', 'pending'), ('uploaded', 'uploaded')], max_length=16),
        ),
    ]
