# Generated by Django 4.2.5 on 2023-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0012_alter_dataupload_file_upload_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataupload',
            options={'verbose_name_plural': 'DataUpload'},
        ),
        migrations.AlterModelOptions(
            name='extracteddata',
            options={'verbose_name_plural': 'Extracted data'},
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='presence_of_open_sewage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='sources_of_water',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='women_and_children_population',
            field=models.CharField(max_length=255),
        ),
    ]
