# Generated by Django 4.2.5 on 2023-09-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0014_dataupload_file_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracteddata',
            options={'verbose_name_plural': 'ExtractedData'},
        ),
        migrations.RemoveField(
            model_name='dataupload',
            name='file_hash',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='file_hash',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='file_upload_status',
            field=models.CharField(choices=[('Progress', 'Progress'), ('uploaded', 'Uploaded'), ('completed', 'Completed')], max_length=16),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='presence_of_open_sewage',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='sources_of_water',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
