# Generated by Django 4.2.5 on 2023-09-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0015_alter_extracteddata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='file_hash',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='past_cases_of_lead_poisoning',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='women_and_children_population',
            field=models.IntegerField(),
        ),
    ]
