# Generated by Django 4.2.5 on 2023-10-21 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('Planning', 'Planning'), ('Testing', 'Testing'), ('Treating', 'Treating')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationStageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('Planning', 'Planning'), ('Testing', 'Testing'), ('Treating', 'Treating')], max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('locations', models.ManyToManyField(to='locations.locations')),
            ],
        ),
    ]
