# Generated by Django 4.2.5 on 2023-10-21 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stagetracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstagetracking',
            name='organizationName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationstage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagetracking.organizationstagetracking'),
        ),
    ]
