# Generated by Django 4.2.5 on 2023-10-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('stagetracking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstagetracking',
            name='locations',
            field=models.ManyToManyField(to='locations.locations'),
        ),
    ]
