# Generated by Django 4.2.5 on 2023-09-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagetracking', '0003_organizationstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstagetracking',
            name='organizationName',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
