# Generated by Django 4.2.5 on 2023-09-15 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stagetracking', '0004_alter_organizationstagetracking_organizationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstagetracking',
            name='organizationName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
