# name: Django CI/CD
# on:
#   push:
#     branches:
#       - main
#       - dev
#       - staging
    
#   pull_request:
#     branches: 
#       - main
#       - dev
#       - staging
  
# jobs:
#   build:
#     runs-on: ubuntu 20.04
#     strategy:
#       max-parallel: 4
#       matrix:
#         python-version: [3.9]
#     steps:   
#     - name: Install requirements 
#       run: pip install -r requirements.txt
#     - name: Check Syntax
#       run: pre-commit run --all-files
      
#     - name: Run Tests
#       run: python3 manage.py test
